#ifndef TETROMINO_BYTETMAP_H
#define TETROMINO_BYTETMAP_H

#define TETROMINO_SIZE  4
#define TETROMINO_LEN   TETROMINO_SIZE * TETROMINO_SIZE

typedef char tetromino_bytemap_t[TETROMINO_SIZE][TETROMINO_SIZE];

#endif // TETROMINO_BYTETMAP_H



