#ifndef SHARED_H
#define SHARED_H

#define TETROMINO_SIZE 4
#define TETROMINO_LEN TETROMINO_SIZE * TETROMINO_SIZE

#define BOARD_HEIGHT 12
#define BOARD_WIDTH 11
#define BOARD_LEN BOARD_HEIGHT * BOARD_WIDTH 


#endif /* SHARED_H */